version: '3.8'

services:
  db_portfolio:
    image: postgres:15
    env_file: ../.env
    volumes:
      - postgres_data_abc:/var/lib/postgresql/data

  web_portfolio:
    build:
      context: ..
      dockerfile: Dockerfile.local
    command: gunicorn core.asgi:application -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:5005 --reload
    volumes:
      - ../:/app
    env_file:
      - ../.env
    depends_on:
      - db_portfolio
    expose:
      - "5005"
    ports:
      - "5005:5005" 

  nginx_renx:
    image: nginx:latest
    ports:
      - "5001:80"  # Пробрасываем только порт 80 наружу
    volumes:
      - ../nginx/nginx.local.conf:/etc/nginx/nginx.conf:ro
      - ../static:/app/static
      # - ./staticfiles:/app/staticfiles
      - ../media:/app/media
    depends_on:
      - web_portfolio

volumes:
  postgres_data_abc:
  