# Generated by Django 5.0.6 on 2025-05-02 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('clients', models.PositiveIntegerField(verbose_name='Кол-во клиентов')),
                ('experience', models.PositiveIntegerField(verbose_name='Опыт работы')),
                ('projects_amount', models.PositiveIntegerField(verbose_name='Кол-во проектов')),
            ],
            options={
                'verbose_name': 'Об о мне',
                'verbose_name_plural': 'Об о мне',
            },
        ),
        migrations.CreateModel(
            name='IntroductionBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('cv_resume', models.URLField(blank=True, null=True, verbose_name='URL резюме')),
            ],
            options={
                'verbose_name': 'Текст (баннер)',
                'verbose_name_plural': 'Текст (баннер)',
            },
        ),
        migrations.CreateModel(
            name='MyInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('specialization', models.CharField(max_length=200, verbose_name='Спецализация')),
                ('location', models.CharField(max_length=255, verbose_name='Местоположение')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='URL instagram')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='URL linkedin')),
                ('telegram', models.URLField(blank=True, null=True, verbose_name='URL telegram')),
                ('whatsapp', models.URLField(blank=True, null=True, verbose_name='URL whatsapp')),
                ('phone', models.CharField(max_length=23, verbose_name='Номер телефона')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Почта')),
            ],
            options={
                'verbose_name': 'Информация обо мне',
                'verbose_name_plural': 'Информаиця обо мне',
            },
        ),
        migrations.CreateModel(
            name='MyWorks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название работы')),
                ('image', models.ImageField(upload_to='works/', verbose_name='Фото сайта')),
                ('tags', models.CharField(max_length=255, verbose_name='Теги')),
                ('description', models.CharField(max_length=500, verbose_name='Описание работы')),
                ('link', models.URLField(blank=True, null=True, verbose_name='URL работы')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Мои проекты',
                'verbose_name_plural': 'Мои проекты',
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(max_length=100, verbose_name='Главный заголовок')),
                ('description', models.CharField(max_length=300, verbose_name='Главный заголовок')),
            ],
            options={
                'verbose_name': 'Резюме',
                'verbose_name_plural': 'Резюме',
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('tool_1', models.CharField(max_length=100, verbose_name='Инструмент 1')),
                ('tool_2', models.CharField(max_length=100, verbose_name='Инструмент 2')),
                ('description', models.CharField(max_length=255, verbose_name='Короткое описание')),
                ('image', models.ImageField(upload_to='about_me/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Скил',
                'verbose_name_plural': 'Скилы',
            },
        ),
        migrations.CreateModel(
            name='ResumeInline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chioce', models.CharField(choices=[('My education', 'My education'), ('Work experience', 'Work experience')], max_length=255, verbose_name='Выбор')),
                ('year', models.CharField(default='2015-2016', max_length=100, verbose_name='Даты')),
                ('position', models.CharField(max_length=255, verbose_name='На кого училась')),
                ('title_of_school', models.CharField(max_length=100, verbose_name='Название училища')),
                ('description', models.CharField(max_length=200, verbose_name='Краткое описание')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_inline', to='settings.resume')),
            ],
            options={
                'verbose_name': 'Доп. информация',
                'verbose_name_plural': 'Доп. информация',
            },
        ),
    ]
