# Generated by Django 5.0.6 on 2025-05-03 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('company_name', models.CharField(max_length=255, verbose_name='название компании')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Почта')),
                ('phone', models.CharField(max_length=23, verbose_name='Номер телефона')),
                ('few_words', models.CharField(max_length=500, verbose_name='доп. информация')),
            ],
            options={
                'verbose_name': 'Заявка на звонок',
                'verbose_name_plural': 'Заявки на звонок',
            },
        ),
        migrations.CreateModel(
            name='FavouriteTools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='tools/', verbose_name='Иконка')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Инструмент',
                'verbose_name_plural': 'Инструменты',
            },
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(max_length=255, verbose_name='Главный заголовок')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='TestimonialsInline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tesimonial/', verbose_name='Фото user')),
                ('fullname', models.CharField(max_length=255, verbose_name='Полное имя')),
                ('position', models.CharField(max_length=255, verbose_name='Позиция')),
                ('company', models.CharField(max_length=255, verbose_name='Название компании')),
                ('url_company', models.URLField(blank=True, null=True, verbose_name='Ссылка на сайт')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('tesimonials', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tesimonials', to='settings.testimonials')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
