# Generated by Django 5.0.6 on 2025-05-03 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_contact_favouritetools_testimonials_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='introductionbanner',
            name='cv_resume',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='URL резюме'),
        ),
    ]
