# Generated by Django 5.0.6 on 2025-05-03 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_alter_testimonialsinline_url_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonialsinline',
            name='url_company',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на сайт'),
        ),
    ]
