# Generated by Django 5.0.6 on 2025-05-03 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_alter_testimonialsinline_url_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='myinformation',
            name='avatar',
            field=models.ImageField(default=1, upload_to='avatar/', verbose_name='Аватар'),
            preserve_default=False,
        ),
    ]
