# Generated by Django 5.0.6 on 2025-05-05 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_myinformation_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='company_name',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='few_words',
            new_name='message',
        ),
        migrations.AlterField(
            model_name='resume',
            name='description',
            field=models.CharField(max_length=300, verbose_name='Главное описание'),
        ),
    ]
